name: build test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: humble
      - run: cargo build