name: build test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    container:
      image: takanotaiga/roboware:amd64

    steps:
      - name: Install Rust and Cargo
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . $HOME/.cargo/env
      - name: install ament-cargo
        run: |
          git clone https://github.com/tier4/cargo-ament-build.git &&
          cd cargo-ament-build &&
          . $HOME/.cargo/env &&
          cargo install --path . &&
          cd .. 

      - name: make workdpace
        run: |
          mkdir -p workspace/src

      - name: Check out repository
        uses: actions/checkout@v3
        with: 
          path: workspace/src/safe_smart_controller_gateway

      - name: clone dep
        run: |
          cd workspace/src/ &&
          git clone https://github.com/hakoroboken/roboware_msg.git &&
          cd ..

      - name: Build tests
        id: build_test
        run: |
          cd workspace/ &&
          . /opt/ros/humble/setup.sh &&
          . $HOME/.cargo/env &&
          colcon build
        shell: bash
